"""Add system_prompt to bot_integrations

Revision ID: 2bf0e9a9148a
Revises: 20260617_01
Create Date: 2026-06-17 11:02:49.893684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf0e9a9148a'
down_revision: Union[str, None] = '20260617_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('bot_integrations')]
    if 'system_prompt' not in columns:
        op.add_column('bot_integrations', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_integrations', 'system_prompt')
    # ### end Alembic commands ###
