"""Add RoleAssignmentHistory

Revision ID: 3539647e7139
Revises: b02f562eab1b
Create Date: 2026-06-17 18:58:48.010539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3539647e7139'
down_revision: Union[str, None] = 'b02f562eab1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=150), nullable=True),
    sa.Column('old_role', sa.String(length=30), nullable=True),
    sa.Column('new_role', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignment_history_actor_user_id'), 'role_assignment_history', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_role_assignment_history_created_at'), 'role_assignment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_assignment_history_id'), 'role_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_role_assignment_history_target_user_id'), 'role_assignment_history', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_assignment_history_target_user_id'), table_name='role_assignment_history')
    op.drop_index(op.f('ix_role_assignment_history_id'), table_name='role_assignment_history')
    op.drop_index(op.f('ix_role_assignment_history_created_at'), table_name='role_assignment_history')
    op.drop_index(op.f('ix_role_assignment_history_actor_user_id'), table_name='role_assignment_history')
    op.drop_table('role_assignment_history')
    # ### end Alembic commands ###
