"""Add MFA columns to User model

Revision ID: 6f15336dd770
Revises: 2bf0e9a9148a
Create Date: 2026-06-17 18:46:14.713387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f15336dd770'
down_revision: Union[str, None] = '2bf0e9a9148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.alter_column('incidents', 'created_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=True)
    op.alter_column('incidents', 'false_positive',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_recovery_codes', sa.JSON(), nullable=True))
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("users")]
    if "status" not in columns:
        op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'SUSPENDED', name='user_account_status', native_enum=False), nullable=False, server_default='ACTIVE'))
    else:
        op.alter_column('users', 'status',
                   existing_type=sa.VARCHAR(length=32),
                   server_default=None,
                   type_=sa.Enum('ACTIVE', 'BLOCKED', 'SUSPENDED', name='user_account_status', native_enum=False),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('ACTIVE', 'BLOCKED', 'SUSPENDED', name='user_account_status', native_enum=False),
               server_default=sa.text("'ACTIVE'::character varying"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('users', 'mfa_recovery_codes')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.alter_column('incidents', 'false_positive',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('incidents', 'created_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'system'::character varying"),
               existing_nullable=True)
    op.alter_column('audit_logs', 'actor',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'security_engineer'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
